// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState} from "react";
import { PlasmicCreateNftForm } from "../plasmicComponents/plasmic/indiart_demo/PlasmicCreateNftForm";

function CreateNftForm_() {


  const [nftData, setnftData] = useState({
    nftname: "",
    nftlink: "",
    listprice: "",
    category:"",
    media:""
})



  const handleChange = (e, field) => {
    let dataField = field
    //console.log('Field: ' + field, 'Value: ', e.target.value)
    setnftData(prevState => {
        return {
            ...prevState,
            [dataField]: e.target.value
        }
    })
    
    console.log(nftData,"nftData");
    
}

const handleChange2 = (name) => { return event => 
        
  setnftData(prevState => {
    return {
        ...prevState,
        [name]: event.target.value
    }
}); 

}

/*
const handleChange2 = (event) => {
  //let dataField = field
  //console.log('Field: ' + field, 'Value: ', e.target.value)
  /*setnftData(prevState => {
      return {
          ...prevState,
          [dataField]: event.target.value
      }
  })*/
  
  //console.log(event.target.value , event.target.name , "event");
//}


  // Use PlasmicCreateNftForm to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicCreateNftForm are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all CreateNftFormProps here, but feel free
  // to do whatever works for you.
  return <PlasmicCreateNftForm 
            nftname={{
                        placeholder: "Enter NFT Name",
                        onChange: (e) => handleChange(e, "nftname")
                      }}

            nftlink={{
                        placeholder: "External NFT Links",
                        onChange: (e) => handleChange(e, "nftlink")
                      }}

            listprice={{
                      placeholder: "Enter Listing Price",
                      onChange: (e) => handleChange(e, "listprice")
                      }}

                      media={
                        <>
                         <div className="select"  
                              onChange={handleChange2("media")}>
                                <select>
                                  <option>Photograph</option>
                                  <option>Art</option>
                                </select>
                        </div>
                        </>
                    }        
                    
                    category={
                      <>
                       <div className="select"
                             name="input2"
                             onChange={handleChange2("category")}
                             >
                              <select>
                                <option name="input2">Still Life</option>
                                <option>Nature</option>
                                <option>Food</option>
                                <option>Monuments</option>
                                <option>Pets and Animals</option>
                              </select>
                      </div>
                      </>
                  }
                  
                  nftpanel={
                    <>
                      <div className="column"> 
                     <figure className="image">
                            <img src='colored-pixels.jpg'/>
                    </figure>
                    </div>
                    </>
                }
  
        />;
}

const CreateNftForm = React.forwardRef(CreateNftForm_);

export default CreateNftForm;
