// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState,useEffect} from "react";
import Steps from './Steps';
import { useNavigate } from 'react-router-dom'
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

const config = {
                    server : "localhost:5000"
                }

                

function CreateNftForm_() {

    let navigate = useNavigate();

    const [nftData, setnftData] = useState({
        name: "",
        creatorname: "Banksy Smith",
        listprice: "",
        category:"Still Life",
        media:"Photograph",
        bundle:"NFT + Framed Photograph"
    })
    
    const [pageState, setpageState] = useState({ status: "initial" })

const handleChange = (name) => { return event => 
        
    setnftData(prevState => {
      return {
          ...prevState,
          [name]: event.target.value
      }
  });
  
  
}  

const onChangeHandler = (event) => {
    console.log(event.target.files[0]);
    setnftData(prevState => {
        return {
            ...prevState,
            file: event.target.files[0],
            fileName: event.target.files[0].name
        }
    })
}




const ipfsUpload = () => {

    setpageState({ status: "loading" });

    console.log(nftData,"nftData");

    const filedata = new FormData();
        
    filedata.append('file',nftData.file);
  	
    console.log("Reached IPFS");

    
    //fetch('http://localhost:5001/api/v0/add', {method: 'POST', body: filedata, mode: 'cors' }).
    fetch('https://ipfswrite.indiart.io/api/v0/add', {method: 'POST', body: filedata, mode: 'cors' }).
	then(function(response,error) {
	
  		if(response)
		{
			return response.json();
		}
		else 
		{
			console.log(error);
		}
		}).then(function(data){
			console.log(data);
            
            setnftData(prevState => {
                return {
                    ...prevState,
                    ipfsHash: data.Hash,
                    ipfsURL: 'http://127.0.0.1:8080/ipfs/' + data.Hash
                      }
                })
                mintNFT(data.Hash)
            })
        }
    
     
const mintNFT = (ipfsHash) => {

    let app = this;
    var url = 'http://'+config.server+'/mintNFT';
    //var url = 'http://'+config.server+'/addminter';
    
       
    console.log("url",url, "nftData",nftData);	
    
                    
  var params = JSON.stringify({              
    ipfsHash: ipfsHash,
    name: nftData.name,
    creatorname: nftData.creatorname,
    media: nftData.media,
    category: nftData.category,
    bundle: nftData.bundle,
    description: nftData.description,
    
        });

    console.log(params,"params");	

  fetch(url, {

    method: 'POST',
    mode: 'cors',

    headers: {
        'Accept': 'application/json',
        'Content-Type':'application/json',
          },	
    body: params
                
            }).then(function(response,error) {
    

                if(response)
            {
                
                return response.json();
            }
        else 
            {
                console.log(error);
            }
            }).then(function(data){

                setnftData(prevState => {

                    console.log("data",data);

                    return {
                        ...prevState,
                        account: data.account,
                        txhash: data.txhash,
                        signature: data.signature,
                        blocknumber: data.blocknumber,
                        tokenID: data.tokenID
                        
                          }
                    })
    
        })   

    }
    

        	
return(
            <div>           
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>

                            <div className="columns">  
                            
                            { nftData.txhash?
                            <div className="column has-text-centered">
                            <h3 className="title is-2 is-family-secondary"> NFT Created Successfully</h3>
                            </div>:
                            <div className="column has-text-centered"> 
                            <h3 className="title is-2 is-family-secondary"> Create a NFT</h3>
                            </div>
                            }
                            
                            </div>
                            
                            <br></br><br></br>    
                            
                            <div className="columns">                               
                            <div className="column">
                                <Steps bar={"create"}/>
                            </div>
                            </div>

                            <br></br>

                            <div className="columns is-centered">    
                            {
                            nftData.txhash?
                            <div className="column has-text-centered is-4">
                            
                            <p className="subtitle is-5 is-family-secondary">Awesome. Now let's list your NFT.</p>
                            <p className="subtitle is-5 is-family-secondary"> Click on 'List for Sale'</p>                           
                            
                            </div>:                           
                            <div className="column has-text-centered is-4">
                            
                            <p className="subtitle is-5">Let's get started! </p>
                            <p className="subtitle is-5">Enter the below details and click "Create NFT" to generate a new NFT</p>                           
                            
                            </div>
                            }    
                            </div>
                            <br></br>
                            
                            

                            <div className="columns is-flex is-centered">    
                                
                                
                               
                                <div className = "column is-5">
                                <nav className="panel">
                                <br></br>

                                
                                {
                                nftData.txhash?
                                <div>
                                    <form className="box">
                                     
                                           <div className="is-family-secondary has-text-centered">

                                               <label className="label title is-4"> Transaction Details </label> <br></br> 

                                               <div className="column">
                                               <b>Creator's Account</b> :<br></br> 
                                               <span className="tag is-large is-success is-light">{nftData.account.slice(20)}...</span><br></br><br></br>
                                               
                                               <b>Transaction hash</b> :<br></br>  
                                               <span className="tag is-large is-success is-light is-multiline">{nftData.txhash.slice(20)}...</span><br></br><br></br>                         
                                               
                                               <b>Signature</b> :<br></br>
                                               <span className="tag is-large is-success is-light">{nftData.signature.slice(20)}...</span><br></br><br></br>
                                               
                                               <b>Block Number</b> :<br></br>
                                               <span className="tag is-large is-success is-light">{nftData.blocknumber}</span><br></br><br></br>
                                               </div>

                                               
                                                <div className="column">
                                                <br></br>   
                                                
                                                <div>
                                                <a className="button is-black" 
                                                    onClick={() => navigate('/wallet')}>
                                                Next: List for Sale</a>
                                                </div>
                                                </div>




                                           </div>
                                 </form>
                                </div>:
                                
                                <div>    
                                

                                <div className="panel-block">                                         
                                <div className="column is-offset-2 is-5">
                                <div className="field">
                                <label className="label is-family-secondary">Title</label>
                                <div className="control">
                                <input className="input" type="text" placeholder="Eg. Everydays.." onChange={handleChange("name")}/>
                                </div>
                                </div>
                                </div>
                                
                                </div><br></br>

                                <div className="panel-block">
                                
                                <div className="column is-offset-2 is-5">
                                <label className="label is-family-secondary">Creator</label><br></br>
                                

                                <div class="box">
                                <article class="media">
                                <div class="media-left">
                                <figure class="image is-48x48">
                             <img className = "is-rounded" src="passport.jpg" alt="Image"/>
                                 </figure>
                                 </div>
                                 <div class="media-content">
                               <div class="content">
                                 <p>
                               <strong>Banksy Smith</strong> <br></br>
                               <small>@banksysmith</small>        
                                 </p>
                                 </div>
                                  </div>
                              </article>
                                </div>
                                
                            
                                
                                </div>
                                </div>    
                                <br></br>


                                <div className="panel-block">
                                <div className="column is-offset-2 is-5">    
                                <div className="field">
                                <label className="label is-family-secondary">Description</label>
                                <div className="control">
                                <textarea className="textarea" placeholder="e.g. Capturing my life one day at a time" onChange={handleChange("description")}></textarea>    

                                </div>
                                </div>
                                </div>

                                </div><br></br>
                                


                                <div className="panel-block">
                                <div className="column is-offset-2">
                                <div className="field">
                                    
                                <label className="label is-family-secondary">Upload Media file (.jpg/.gif)</label>
                                
                                <div className="file is-boxed has-name">
                                    <label className="file-label">
                                        <input className="file-input" type="file" name="nftfile" onChange={onChangeHandler}/>
                                                <span className="file-cta">
                                                    <span className="file-icon">
                                                        <i className="fa fa-upload"></i>
                                                    </span>
                                                    <span className="file-label">
                                                    <b>Select File</b>
                                                    </span>

                                                </span>
                                                
                                                <br></br><br></br>
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{nftData.fileName}
                                    </label>
                                </div>
                                </div>
                                </div>
                                </div><br></br>


                                <div className="panel-block">
                                <div className="column is-offset-2 is-5">
                                <div className="field">
                                <label className="label is-family-secondary">Media</label>
                                
                                <div className="select"  
                                    onChange={handleChange("media")} default="Photograph">
                                        <select>
                                            <option>Photograph</option>
                                            <option>Art</option>
                                        </select>

                                 </div>

                                </div>
                                </div>
                                </div><br></br>

                                <div className="panel-block">
                                <div className="column is-offset-2 is-5">
                                <div className="field">
                                <label className="label is-family-secondary">Category</label>
                                
                                <div className="select"
                                    onChange={handleChange("category")} default="Still Life">
                                        <select>
                                            <option name="input2">Still Life</option>
                                            <option>Nature</option>
                                            <option>Food</option>
                                            <option>Monuments</option>
                                            <option>Pets and Animals</option>
                                        </select>

                                </div>
                                </div>
                                </div>
                                </div><br></br>


                                <div className="panel-block">
                                <div className="column is-offset-2 is-5">
                                <div className="field">
                                <label className="label is-family-secondary">Items included</label>
                                
                                <div className="select"  
                                    onChange={handleChange("bundle")} default="NFT + Framed Photograph">
                                        <select>
                                            <option>NFT + Framed Photograph</option>
                                            <option>NFT + Art Piece</option>
                                            <option>NFT + Digital Form</option>
                                        </select>
                                 </div>
                                 </div>   
                                </div>
                                </div><br></br>

                                     
                                
                                <div className="column is-offset-4">
                                <br></br>   
                                
                                <a className="button is-black" 
                                        onClick={() => ipfsUpload()}>
                                Create NFT</a>

                                </div>
                                </div>
                                
                                }
                                <br></br>
                            
                                </nav>
                                </div>
                                

                                

                                <div className = "column is-4 has-text-centered">
                                    
                                <div className="panel has-text centered">
                                
                                    
                                {
                                nftData.txhash?    
                                <div>
                                </div>:    
                                <div className="panel-body">
                                <div className="form">
                                
                                <div className="field">
                                <br></br><br></br>
                                <label className="label is-family-secondary">Creator's Key</label>
                                
                                <span className="tag is-light is-large">0x20263d77C79efaCE77F8fAB3D5649b444d2c349F</span>
                                </div>
                                
                                </div>
                                
                                <br></br><br></br>
                                </div>
                                }
                                
                                

                                {
                                nftData.txhash?    
                                        
                                 <form className="box">
                                 <figure className="image is-square">
                                 <img src={nftData.ipfsURL}/>
                                 </figure>
                                 </form>:  
                                 
                                 pageState.status == "loading"?

                                 <form className="box">
                                 <figure className="image is-square">
                                 <img src='loading-small.gif'/>
                                 </figure>
                                 </form>:

                                <form className="box">
                                <figure className="image is-square">
                                <img src='colored-pixels.jpg'/>
                                </figure>
                                </form>
                                } 

                                </div>
                            </div>
                            <br></br><br></br><br></br><br></br><br></br><br></br>
                      
            </div>
            </div>
)


}

const CreateNftForm = React.forwardRef(CreateNftForm_);

export default CreateNftForm;
