// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicEmailVerified } from "../plasmicComponents/plasmic/indiart_demo/PlasmicEmailVerified";

function EmailVerified_(props, ref) {
  // Use PlasmicEmailVerified to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicEmailVerified are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all EmailVerifiedProps here, but feel free
  // to do whatever works for you.
  return <PlasmicEmailVerified root={{ ref }} {...props} />;
}

const EmailVerified = React.forwardRef(EmailVerified_);

export default EmailVerified;
