// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useState, useEffect } from "react";

import { useNavigate } from "react-router-dom";
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

//function HomeScam_() {

const HomeScam = (props) => {
  const navigate = useNavigate();

  return (
    <div className="bg-img">
      <div className="box bg-img">
        <div className="columns is-centered">
          <div className="column has-text-centered">
            <figure className="image ">
              <img src="banner.gif"></img>
            </figure>
            <div className="columns is-overlay is-centered">
              <div className="column is-4 has-text-centered">
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                <div className="columns">
                  <div className="column ">
                    <a
                      className="button is-large is-black "
                      onClick={() => {
                        if (props.appState.account) {
                          navigate("/proposer");
                        } else {
                          alert("Please Connect your Wallet to Proceed")
                        }
                      }}
                    >
                      Report a Scam{" "}
                    </a>
                  </div>
                  <div className="column">
                    <a
                      className="button is-large is-link "
                      onClick={() => {
                        if (props.appState.account) {
                          navigate("/validator");
                        } else {
                          alert("Please Connect your Wallet to Proceed")
                        }
                      }}
                    >
                      {" "}
                      Validator Login
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

//const HomeScam = React.forwardRef(HomeScam_);

export default HomeScam;
