// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState,useEffect} from "react";
import { useNavigate,useParams } from 'react-router-dom';
import Steps from './Steps';
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

const config = {
                    server : "localhost:5000"
                }



function SellNftForm_(props,ref) {

 const navigate = useNavigate();   

const [price, setprice] = useState({ });

const [listData, setlistData] = useState({ })



console.log("props",props);

const token = props.token.token;

var tmp = new Date( token.tokenDets.timestamp);

var timestamp = tmp.toLocaleString();

const listNFT = () => {

    let app = this;
    var url = 'http://'+config.server+'/listNFT';
    
       
  var params = JSON.stringify({              
    tokenID: token.tokenID,
    price: price,
            });

    console.log(params,"params");	

  fetch(url, {

    method: 'POST',
    mode: 'cors',

    headers: {
        'Accept': 'application/json',
        'Content-Type':'application/json',
          },	
    body: params
                
            }).then(function(response,error) {
    

                if(response)
            {
                
                return response.json();
            }
        else 
            {
                console.log(error);
            }
            }).then(function(data){

                console.log("data",data);

                let expiryTime = new Date(data.expiryTime*1000)
                let listingTime = new Date(data.listingTime*1000)


                setlistData(prevState => {
    
                    return {
                        ...prevState,
                        creator: data.creator,
                        price: data.price,
                        signature: data.signature,
                        blocknumber: data.blocknumber,
                        tokenID: data.tokenId,
                        txhash: data.txhash,
                        expiryTime: expiryTime.toLocaleString(),
                        listingTime: listingTime.toLocaleString()
                          }
                        
                    })  
    
        })   

    }


const handleChange = () => { return event => 
        
        setprice(event.target.value)

          }
    
      
        	
return(
            <div>           
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            <div className="columns">  
                            <div className="column is-offset-5">
                            { 
                            listData.txhash?
                                <h3 className="title is-2 is-family-sans-serif"> NFT Successfuly Listed</h3>    
                                :<h3 className="title is-2 is-family-sans-serif"> List for Sale</h3>
                            }
                            </div>
                            </div>
                            <div className="columns">                               
                            <div className="column">
                                <Steps bar="list"/>
                            </div>
                            </div>
                            <div className="columns">  
                            <div className="column">
                            
                            </div>
                            </div>
                            <div className="columns is-centered">  
                            
                            {
                            listData.txhash?   
                            <div className="column has-text-centered">
                            <p className="subtitle is-5">Enter listing price (in INR) and list for sale </p>
                            </div>:
                            <div className="column has-text-centered">
                            <p className="subtitle is-5 is-family-secondary">Your token is now listed on the marketplace for sale.</p>
                            <p className="subtitle is-5 is-family-secondary">Now let's check out the marketplace and buy a NFT </p>
                            </div>
                            }
                            </div>
                            
                            
                            

                            

                            <div className="columns is-flex is-centered is-vcentered">    

                            <div className = "column is-4">

                            <form className="box">
                            <figure className="image is-square">
                            <img src={token.tokenURI}/>
                            </figure>
                            </form>


                            </div>

                                
                                
                               
                                <div className = "column is-5 ">
                                <nav className="panel">
                                <br></br>
  
                                {
                                    
                                listData.txhash?
                                
                                <div>
                                    <form className="box">
                                     
                                           <div className="is-family-secondary has-text-centered">


                                               <b>Transaction hash</b> :<br></br>  
                                               <span className="tag is-success is-large is-light is-multiline">{listData.txhash.slice(20)}...</span><br></br><br></br>                         
                                               
                                               <b>Signature</b> :<br></br>
                                               <span className="tag is-success is-large is-light">{listData.signature.slice(20)}...</span><br></br><br></br>
                                               
                                               <b>Block Number</b> :<br></br>
                                               <span className="tag is-large is-success is-light">{listData.blocknumber}</span><br></br><br></br>
                                               

                                               <b>Listing Time</b> :<br></br>  
                                               <span className="tag is-large is-success is-light is-multiline">{listData.listingTime}</span><br></br><br></br>                         
                                               
                                               <b>Expiry Time</b> :<br></br>
                                               <span className="tag is-large is-success is-light">{listData.expiryTime}</span><br></br><br></br>
                                               
                                               <b>Price</b> :<br></br>
                                               <span className="tag is-large is-success is-light">₹ {listData.price}</span><br></br><br></br>
                                               

                                             </div> 

                                                <div className="column has-text-centered">
                                                <br></br>   
                                                
                                                <div>
                                                <a className="button is-black" 
                                                    onClick={() => navigate('/marketplace')}>
                                                Next: View Marketplace</a>
                                                </div>
                                                </div>

                                 </form>
                                
                                </div>:
                                
                                
                                <div className="column is-10 is-offset-1">
                                <br></br><br></br>    
                                <div className="panel-block ">                                         
                                <label className="label is-family-primary has-text-centered">Enter Listing Price  </label>
                                
                                <div className="field">
                                
                                <div className="column is-offset-1">
                                <div className="control has-icons-left">
                                <input className="input" type="text" placeholder=" Price in INR" onChange={handleChange()}/>
                                <span className="icon is-small is-left">
                                <i className="fa-solid fa-indian-rupee-sign"></i>
                                </span>
                                </div>
                                </div>
                                </div>
                                </div>


                                <div className="card is-rounded">
                                    

                                <div className="card-content">
                
                                <div className="media">

                                <div class="media-left">
                                <figure class="image is-48x48">
                                <img className ="is-rounded" src="passport.jpg" alt="Placeholder image"/>
                                </figure>
                                </div>    

                                <div className="media-content">

                                <h2 class="title is-4">{token.tokenDets.name}</h2>

                                <h2 class="subtitle is-6">{token.tokenDets.creatorname}</h2>
                                
                                </div>
                                
                                </div>

                                <div className="content">
                                {token.tokenDets.description}  <br></br><br></br>
                               <b>Media type :</b>&nbsp;&nbsp;{token.tokenDets.media} <br></br>
                               <b>Category :</b>&nbsp;&nbsp;{token.tokenDets.category} <br></br>
                               <b>Included Items :</b>&nbsp;&nbsp;{token.tokenDets.bundle} <br></br>
                               <b>Created  :</b>&nbsp;&nbsp; {timestamp} <br></br>
                                
                                </div>
                                
                                </div>
                                </div>
                                
                                </div>
                                
                                }
                                
                                     
                                
                                
                                <div className="column has-text-centered">
                                   
                                {
                                listData.txhash?    
                                <div></div>:
                                <a className="button is-black" onClick={ () => {listNFT()}}>
                                List for Sale</a>
                                }
                                </div><br></br>


                            
                                </nav>
                                </div>
                                

                                
                            </div>                             <br></br><br></br><br></br><br></br><br></br><br></br>
                      
                
            </div>
)


}

const SellNftForm = React.forwardRef(SellNftForm_);

export default SellNftForm;

//<img src='loading-small.gif'/>