// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
//import { mergeProps } from "@plasmicapp/react-web/dist/react-utils";
import * as React from "react";
import {useState,useEffect} from "react";
import { useNavigate } from 'react-router-dom';
import Steps from './Steps';
//import { useMoralis, useMoralisFile} from "react-moralis";

//import InputField from './InputField';

const config = {
                    server : "localhost:5000"
                }

                let count = 0;

function Mywallet_(props) {

    const navigate = useNavigate()

    let walletData = props.walletData;
    let setwalletData = props.setwalletData;
    let token = props.token;
    let settoken = props.settoken;

    


    useEffect(() => {
        
    var url = 'http://'+config.server+'/getallNFTs';
       
    console.log("url",url);	
  
    //console.log("walletData",walletData);
    
    //if (count == 0 )
      //  {
        //    count  = 1;
  fetch(url, {

    method: 'POST',
    mode: 'cors',

    headers: {
        'Accept': 'application/json',
        'Content-Type':'application/json',
          },	
    
                
            }).then(function(response,error) {
    

                if(response)
            {
                
                return response.json();
            }
        else 
            {
                console.log(error);
            }
            }).then(function(data){

                console.log("tokens",data);

                
                setwalletData(prevState => {
                    return {
                        ...prevState,
                        tokens : data
                    }
                });
                //walletData.tokens.reverse()
                console.log(data.tokens,"tokens here");
        })
       },[]) 
    //})
    //}
    //},[count])
    
    
    const viewToken = (token) => {

    settoken(prevState => {
        return {
            ...prevState,
            token : token
        }
    });
    
    navigate('/sellNftForm')
    
};    




        	
return(
            <div>           
                            <div className="columns">                               
                            <div className="column">
                            </div>
                            </div>
                            
                            <div className="columns">  
                            <div className="column">
                            <div className="has-text-centered">
                            <h3 className="title is-2 is-family-sans-serif"> My Portfolio</h3>
                            </div>
                            </div>
                            </div>
                            <div className="columns">  
                            <div className="column">
                            
                            </div>
                            </div>

                            <div className="columns">  
                            <div className="column">
                            <Steps bar={"wallet"}/>

                            </div>
                            </div>
                            <div className="columns">  
                            <div className="column">
                            
                            </div>
                            </div>

                            <div className="columns is-centered">  
                            
                            <div className="column has-text-centered is-4">
                            
                            <p className="subtitle is-5 is-family-secondary">The My Portfolio page lists all NFTs owned by you </p>
                            <p className="subtitle is-5 is-family-secondary">Click on 'List for Sale' corresponding to the NFT to be listed </p>
                            
                            </div>
                                
                            </div>
                            <div className="columns">  
                            <div className="column">
                            
                            </div>
                            </div>

                            

                                <div className="columns is-multiline">    
                            
                                   
                                <div className = "column is-8 is-offset-2">
                                 


                                <nav className="panel">
                                
                                <form className="box">
                                
                                {
                                walletData.tokens?
                                
                                <div className="columns is-multiline">
                                   
                                {    
                                
                                walletData.tokens.tokens.map((wallet,index) => {


                                    return (

                                <div key={index} className="column is-4 ">
                                <div className="card is-rounded">
                                    
                                <div className="card-image">

                                <figure className="image">
                                <img src={'./potrait'+index+'.jpeg'} alt={'./potrait.jpeg'}/>
                                </figure>            

                                </div>

                                <div className="card-content overlay">
                
                                <div className="media">

                                <div class="media-left">
                                <figure class="image is-48x48">
                                <img className ="is-rounded" src="passport.jpg" alt="Placeholder image"/>
                                </figure>

                                
                                </div>    

                                <div className="media-content">

                                <h2 class="title is-6">{wallet.tokenDets.name}</h2>

                                <h2 class="subtitle is-6">{wallet.tokenDets.creatorname}</h2>
                                
                                </div>

                                <div class="media-right">
                                <h2 class="title is-6">Price</h2>

                                ₹{wallet.tokenDets.listprice}
                                </div>  

                                
                                </div>
                                
                                <div className="column has-text-centered">        
                                {
                                 wallet.tokenDets.listprice != 0?   
                                <a className="button is-black" disabled  
                                 >List for sale</a>:
                                <a className="button is-black"  
                                
                                onClick={ () => {viewToken(wallet)}} >List for sale</a>

                                }
                                </div>            

                                
                                </div>

                                </div>
                               
                                
                                                  
                                 </div>    
                                           
                                        )    
                                   
                               
                                
                                })
                            }
                                </div>:

                                <div>
                                    Loading your Portfolio..
                                </div>
                            }    
                                </form>


                            
                                </nav>
                                 
                                </div>
                                
                            </div>                            <br></br><br></br><br></br><br></br><br></br><br></br>
                      
                
            </div>
)


}

const Mywallet = React.forwardRef(Mywallet_);

export default Mywallet;

//<img src='loading-small.gif'/>